name: deploy-lambda

on:
  push:
    branches:
      - terraform-aws-stage1

jobs:
  run-checks:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v3.3.0
        - name: Setup Python
          uses: actions/setup-python@v4.5.0
          with:
            python-version: '3.9'
        - name: Install make
          run: sudo apt install make -y
        - name: Install Application Requirements
          run: make requirements
        - name: Install Dev Dependencies
          run: make dev-setup
        # - name: Run Checks
        #   run: make run-checks
  deploy:
    environment: dev
    needs: run-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.3.0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Format
        working-directory: ./terraform
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        working-directory: ./terraform
        id: init
        run: terraform init